export const POSITION = [
    "GARDIEN",
    "DEFENSEUR DROIT",
    "DEFENSEUR GAUCHE",
    "DEFENSEUR CENTRAL",
    "MILIEU DEFENSIF",
    "MILIEU CENTRE",
    "MILIEU OFFENSIF",
    "MILIEU GAUCHE",
    "MILIEU DROIT",
    "AILIER DROIT",
    "AILIER GAUCHE",
    "ATTAQUANT AXIAL"
];